### ISSUE TITLE
Use decimal numbers instead of hex to specify the APIs to test

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/xbox_kernel_test_suite#107]
In my opinion, it would make more sense to me if the APIs to tests could be specified in decimal instead of hex. That's how they are listed in the xboxdevwiki, and it would also avoid the need for a conversion. Note that, if this is accepted, it will break old config.txt files that still use hex.

**Comment by RadWolfie** [comment]
I don't mind using either hexadecimal or decimal values for tests/tests-exclude options. Although in my opinion, using decimal is easier and able to follow through like ergo720 said and looking at the nxdk's [xboxkrnl.exe.def](https://github.com/XboxDev/nxdk/blob/master/lib/xboxkrnl/xboxkrnl.exe.def) file as well.
