### ISSUE TITLE
XBE fails to boot from within Cxbx-Reloaded

### ISSUE THREAD

**Issue by x1nixmzeng** [Cxbx-Reloaded/xbox_kernel_test_suite#28]
Hello

I'm having a number of problems getting this running.

The published XBE files seem to fail on "pb_init" with the latest Cxbx-Reloaded build - which I've double-checked after building my own with some extra logging:

 ```
   switch(pb_init()){
        case 0: break;
        default:
            print("Failed on pb_init");
            XSleep(2000);
            XReboot();
            return;
}
```

**Comment by x1nixmzeng** [comment]
Commenting out all the `pb_*` code seems to actually start the tests

**Comment by x1nixmzeng** [comment]
`xboxkrnl::RtlInitAnsiString` seems to be called with a garbage pointer

Maybe `getCurrentDirString` failing ot read the value of `XeImageFileName` from the emulator, returning a dud-current path, although I can't be sure

This test is the broken one:

```c
void test_NtClose(){
    const char* func_num = "0x00BB";
    const char* func_name = "NtClose";
    HANDLE handle;
    NTSTATUS status;
    OBJECT_ATTRIBUTES obj;
    IO_STATUS_BLOCK isb;
    ANSI_STRING obj_name;
    char filepath[200];
    BOOL tests_passed = 0;

    print_test_header(func_num, func_name);

    XConvertDOSFilenameToXBOX("./default.xbe", filepath);
    RtlInitAnsiString(&obj_name, filepath);

    obj.RootDirectory = NULL;
    obj.Attributes = OBJ_CASE_INSENSITIVE;
    obj.ObjectName = &obj_name;

    status = NtCreateFile(
    &handle,
    GENERIC_READ,
    &obj,
    &isb,
    NULL,
    FILE_ATTRIBUTE_NORMAL,
    0,
    FILE_OPEN,
FILE_SYNCHRONOUS_IO_NONALERT);
```

> 
> [0x2CC0] KRNL: RtlInitAnsiString(
>  OUT DestinationString  : 0x0457F958
>    SourceString         : (char *)0x0457F890 = "ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ8\xFFFFFFF9W\x04šÁ\x03"
> );
> [0x2CC0] KRNL: NtCreateFile forwarding to "IoCreateFile"...
> [0x2CC0] KRNL: IoCreateFile(
>  OUT FileHandle         : 0x0457F97C
>    DesiredAccess        : 80000000
>    ObjectAttributes     : 0x0457F968 -> OBJECT_ATTRIBUTES* {
>    .RootDirectory        : 00000000
>    .ObjectName           : 0x0457F958 -> STRING* {
>    .Length               : 9B
>    .MaximumLength        : 9C
>    .Buffer               : (char *)0x0457F890 = "ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ8\xFFFFFFF9W\x04šÁ\x03"}
>    .Attributes           : 40}
>  OUT IoStatusBlock      : 0x0457F960
>    AllocationSize       : 0x00000000
>    FileAttributes       : 80
>    ShareAccess          : 0
>    Disposition          : (CREATE_DISPOSITION)0x00000001 = FILE_OPEN
>    CreateOptions        : (CREATE_OPTION)0x00000020 = FILE_SYNCHRONOUS_IO_NONALERT
>    Options              : 0
> );
> [0x2CC0] FILE: IoCreateFile Corrected path...
>   Org:"ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ8ùWšÁ"
>   New:"$XbePath\ÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ8ùWšÁ"
> [0x2CC0] WARN: KRNL: IoCreateFile Failed! (STATUS_OBJECT_NAME_INVALID)
> 
> [0x2CC0] KRNL: IoCreateFile returns C0000033
> [0x2CC0] KRNL: NtClose(
>    Handle               : 00000000
> );
> [0x2CC0] KRNL: NtClose returns C0000008

**Comment by ghost** [comment]
I'm unable to reproduce this, on https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/6b6f6265f5ffc87c6c3d9c7037345b64ecc76228 the published xbe (avoid system crash in Av Tests) works fine for me and all tests but one succeed. The only one that fails is RtlEqualUnicodeString, which is already documented by @PatrickvL in #24 
[KrnlDebug-d.txt](https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/files/1903344/KrnlDebug-d.txt)
[KrnlDebug-r.txt](https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/files/1903345/KrnlDebug-r.txt)

**Comment by x1nixmzeng** [comment]
Thanks for your logs @ergo720

I ended up removing `%APPDATA%\Cxbx-Reloaded` and all is well

Edit

As mentioned on the wiki: 
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/wiki/Frequently-Asked-Questions-(FAQ)#a-game-stopped-working-after-i-updated-cxbx-reloaded
