### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by GXTX** [Cxbx-Reloaded/xbox_kernel_test_suite#56]
_Recently_ NXDK moved to a new std library which caused this program to not be able to build.

```
[ LD       ] main.exe
lld: error: /home/wsl/Xbox/SDK/nxdk/samples/xbox_kernel_test_suite/main.obj: undefined symbol: _strtok_r
/home/wsl/Xbox/SDK/nxdk/samples/xbox_kernel_test_suite/../../Makefile:113: recipe for target 'main.exe' failed
make: *** [main.exe] Error 1
```

**Comment by JayFoxRox** [comment]
For the record: the new std lib (pdclib) was in review for weeks, so this didn't come out of nowhere. The new lib is much more complete, stable and cleaner.

The easiest solution is to copy the old source files from nxdk to this project. Ideally you'd stick to standard functions that are part of a libc (`strtok_r` is a POSIX extension) or convince upstream pdclib (https://github.com/DevSolar/pdclib) to change their code.

**Comment by Luca1991** [comment]
Okay, I'll give a look at this issue tomorrow. Are there any other undefined symbols than strtok? 


Edit: to Patrick, and every other cool ppl that was following my work in this repo (and on CxBx-R repo) earlier: sorry for being disappeared that way, I'm still extremely busy completing last couple of exams, following some private projects and looking for a job... I'll be reachable on discord if needed.
