### ISSUE TITLE
RtlAnsiStringToUncodeString hangs on real hardware

### ISSUE THREAD

**Issue by GXTX** [Cxbx-Reloaded/xbox_kernel_test_suite#57]
Using a solution proposed in #56 (copying the needed function) I am able to test further and on real hardware I am hanging on `RtlAnsiStringToUnicodeString`.

**Comment by JayFoxRox** [comment]
https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/blob/cf223ce5902285de95221045ef8bcdbe6625cdb8/rtl_tests.c#L29-L36

`src_str` is never initialized ([of type ANSI_STRING; click for MSDN](https://docs.microsoft.com/en-us/windows/desktop/api/ntdef/ns-ntdef-_string)), so its `Buffer` pointer and `MaximumLength` might be garbage.

---

Additionally, the same is true for `dest_str`. By passing `0` (`FALSE`) as the third argument (`AllocateDestinationString`), this function will write to a garbage pointer.
