### ISSUE TITLE
Consider switching to std::vector

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/xbox_kernel_test_suite#66]
Currently, the test suite is using a custom vector implementation provided in `vector.h` and `vector.cpp`. However, it's limited: for example, it doesn't have an erase function and it's hard-coded to use integer types for its elements. I believe that nxdk now offers a native `std::vector` implementation in nxdk-libcxx, as also evidenced by NevolutionX (an app built with nxdk) which is already using them here https://github.com/dracc/NevolutionX/blob/37b3a280cb5269168d1120dbfc370e0968ab3cb7/main.cpp#L33. To solve the above limitations, I suggest to switch to the `std::vector` implementation provided by nxdk.

**Comment by RadWolfie** [comment]
It depends on how bad we need standard vector. As far I had see, only `tests_to_run` variable is using vector.
