### ISSUE TITLE
tests_to_run is freed without allocation

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/xbox_kernel_test_suite#8]
When running under Cxbx-Reloaded, it can't find the config.txt file (even though I put it next to the xbe) but in any case, that leads to not allocating `tests_to_run`. After running all tests, `tests_to_run` is still freed. That's a bug. I've fixed the Cxbx-Reloaded kernel to be a little more resilient against that, but it's still a bug that should be fixed.

**Comment by Luca1991** [comment]
Yeah, you are right! This is something I'll fix soon.

**Comment by Luca1991** [comment]
@PatrickvL I think we can close this now. Waiting for your confirmation ;)
